<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('order_messages', function (Blueprint $table) {
            $table->id();

            // ── Thread ownership ───────────────────────────────────────────────
            $table->foreignId('order_id')
                  ->constrained('orders')
                  ->cascadeOnDelete();

            // Who sent this message — admin or customer.
            // restrictOnDelete: don't silently wipe message history if a
            // user account is deleted. Handle account removal explicitly.
            $table->foreignId('user_id')
                  ->constrained('users')
                  ->restrictOnDelete();

            // ── Message type ───────────────────────────────────────────────────
            // mockup    → admin uploaded a photo of the physical / rendered mockup
            // approval  → customer clicked Approve (body can hold a short note)
            // revision  → customer submitted a redesigned version from the builder
            // note      → plain text message: questions, clarifications, reminders
            $table->enum('type', [
                'mockup',
                'approval',
                'revision',
                'note',
            ]);

            // ── Content fields — all nullable, populated based on type ─────────

            // Plain text — used by: note, approval (optional), revision (optional)
            $table->text('body')->nullable();

            // Mockup photo path in Laravel Storage (public disk).
            // Used by: mockup
            // e.g. "mockups/AC-20250328-0042/v1.jpg"
            $table->string('image_path', 255)->nullable();

            // Full element array — same shape as order_designs.design_json.
            // Used by: revision — stores the updated design the customer submitted.
            $table->json('design_json')->nullable();

            // Canvas PNG snapshot generated by Fabric.js toDataURL().
            // Used by: revision — shown as thumbnail in the thread.
            // e.g. "revisions/AC-20250328-0042/v2.png"
            $table->string('snapshot_path', 255)->nullable();

            $table->timestamps();

            // ── Indexes ────────────────────────────────────────────────────────
            // Most queries load the full thread for one order in created_at order.
            $table->index(['order_id', 'created_at']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('order_messages');
    }
};