<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('saved_designs', function (Blueprint $table) {
            $table->id();

            // ── Ownership ──────────────────────────────────────────────────────
            $table->foreignId('user_id')
                  ->constrained('users')
                  ->cascadeOnDelete();
            // cascade: deleting an account wipes their saved designs too

            // ── Identity ───────────────────────────────────────────────────────
            $table->string('name', 120)->default('My Design');
            // User-editable label shown in /account/designs gallery

            $table->enum('product_slug', ['bracelet', 'necklace', 'keychain']);

            // ── Design data ────────────────────────────────────────────────────
            // Full element array — same shape as order_designs.design_json
            $table->json('design_json');

            // PNG snapshot generated by Fabric.js toDataURL(), stored via
            // Laravel Storage. Shown as thumbnail in the designs gallery.
            $table->string('snapshot_path', 255)->nullable();

            // ── Canvas state (mirrors order_designs columns exactly) ───────────
            // Stored so the builder can fully restore the design on load.
            $table->string('str_color', 10)->nullable();   // string / cord colour
            $table->string('str_type', 20)->nullable();    // Elastic | Cord | Wire | Chain
            $table->string('clasp', 20)->nullable();       // none | lobster | toggle
            $table->tinyInteger('keychain_strands')->default(1); // 1–3
            $table->string('ring_type', 20)->nullable();   // ring | heart | carabiner | ballchain
            $table->string('ring_color', 10)->nullable();
            $table->string('letter_bg_color', 10)->nullable();
            $table->string('letter_text_color', 10)->nullable();
            $table->string('letter_shape', 10)->nullable(); // square | round

            $table->timestamps();
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('saved_designs');
    }
};